name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: rust:1.88
    steps:
      - uses: actions/checkout@v4
      - run: cargo build
      - run: cargo test

  lint:
    runs-on: ubuntu-latest
    container: rust:1.88
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    container: rust:1.88
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
